### ISSUE TITLE
Pie throws panic if iop.proc is nil

### ISSUE THREAD

**Issue by lonelycode** [natefinch/pie#1]
Not sure why this is, it could just be that the process is never assigned properly when it is created, this is using a python script as an external RPC plugin, everything works until it tries to close the process and then it explodes at this point: 

```
if err := iop.proc.Signal(os.Interrupt); err != nil {
    return err
}
```

Not sure if this is just the way I am handling it (I'm trying to use an external, non-golang plugin writen in python, [gist is here](https://gist.github.com/lonelycode/14a6f2dc6798cd38b1a6)

**Comment by natefinch** [comment]
Thanks for the bug report.  I'll try to figure out why the process is nil. I wonder if I have a logic error somewhere.  I don't think just avoiding the panic on cleanup is the right approach, instead we should figure out why proc is nil at that point, and try to prevent it from being nil in the first place.

Also, thanks a ton for providing an example python script to use with this.  I'm not a python expert, but I really wanted to try using a python script as a plugin to show how this package supports plugins from different languages.

**Comment by natefinch** [comment]
Actually, looks like this is happening with my example programs as well...

**Comment by natefinch** [comment]
run `go get -u github.com/natefinch/pie` (or git pull) and try again... there was a bug I introduced when refactoring for tests, ironically.  I'm going to add more tests to catch similar problems in the future.

**Comment by lonelycode** [comment]
Allready did - as soon as the fix went in :-)

Works like a charm.

Since this uses stdio though, it's prone to blocking if one RPC call takes too long, I think that's why most RPC implementations instantly asume that you are going to run a TCP server, since you can then fork out to handle load and long-running replies.

Unless I've totally set this up wrong :-/

**Comment by natefinch** [comment]
It's actually not blocking.  The RPC server starts a goroutine for each request.  See here: https://github.com/golang/go/blob/release-branch.go1.4/src/net/rpc/server.go#L476

**Comment by natefinch** [comment]
You can test it out by adding a long wait in your plugin's function, and using rpc.Client.Go() to make a few requests in parallel.    

The code for the master process would look something like this:

``` go
package main

import (
    "log"
    "net/rpc/jsonrpc"

    "github.com/natefinch/pie"
)

func main() {
    path := "plugin.py"
    client, err := pie.StartProviderCodec(jsonrpc.NewClientCodec, os.Stderr, path)
    if err != nil {
        log.Fatalf("Error running plugin: %s", err)
    }
    defer client.Close()

    var reply1 string
    call1 := client.Go("Plugin.SayHi", "one", &reply1, nil)

    var reply2 string
    call2 := client.Go("Plugin.SayHi", "two", &reply2, nil)

    var reply3 string
    call3 := client.Go("Plugin.SayHi", "three", &reply3, nil)

    count := 0
    for count < 3 {
        select {
        case <-call1.Done:
            log.Printf("#1 is done, reply: %s", reply1)
            count++
        case <-call2.Done:
            log.Printf("#2 is done, reply: %s", reply2)
            count++
        case <-call3.Done:
            log.Printf("#3 is done, reply: %s", reply3)
            count++
        }
    }
}
```

You'll see that the total runtime is approximately equal to one of the waits, not 3.

**Comment by natefinch** [comment]
Oh sorry... you're talking about using python's JSON RPC... I don't know about that... I'm not much of a pythonista.  I would imagine there's a way to do it such that the calls don't have to be blocking.

**Comment by lonelycode** [comment]
Ah yes, I did something similar but in a more roundabout way, the server
can take many requests and all that works fine and executes in parallel

When I ran this with wait commands it ran them all very quickly, but the
replies all arrived in order.

So the underlying script or app will need to be threaded in order to reply
appropriately but since the input being stdio there's only one in and one
out, right?

**Comment by natefinch** [comment]
There's one and only one in and out, but that's no different than the one and only one TCP connection to a web-based RPC server, too.  I presume pretty much every RPC server implementation has a way to accept more than one connection at a time, or otherwise force serialization... I'm honestly not an RPC expert... but I trust the go implementation is doing the right thing.

**Comment by lonelycode** [comment]
Right, I have tested this just to be sure.

RPCServer can handle out-of-order responses over STDIO.

Which is great, I've created a new python demo which uses threaded handlers for RPC calls over STDIN with a random timer variable to make sure that the responses are printed out-of-order.

The new gist for this demo plugin is [here](https://gist.github.com/lonelycode/7983389b305e55da5b27) with the matching golang master [here](https://gist.github.com/lonelycode/51158a5e24137b18fa00). It might help others :-)

Thanks for all the help, we may be using this in our application soon!

**Comment by natefinch** [comment]
That's awesome.  I'm glad it's working out so well for you.  I'd love to see the end result, if it's open sourced.  

Would you care to make a PR with the python code and matching master code?  I moved the examples into a single subdirectory, so you could just add those two files to examples/python/master_python.  I could do this myself, but I figured I'd offer you the opportunity to do a PR, to get proper credit (I'd credit you anyway, but this way it's is more "official").  I'd be super happy to have an example of a python plugin working with a go program in the actual repo.

**Comment by lonelycode** [comment]
Thanks - will do a PR in the morning :-)

The project is already open sourced - it's Tyk (https://tyk.io) we're
looking for a good way to add plugins to it, so this approach suits us well.

**Comment by natefinch** [comment]
Awesome.  Let me know if there's anything I can do to help.   Actually, here's one thing, typo on the front page of tyk.io: "Swagger and API Blubrint suport".  I went to go make a PR against the website, but couldn't find the code for it (perhaps it's private?).

**Comment by lonelycode** [comment]
It is 😊

Thanks for pointing it out, will make the change…

**Comment by natefinch** [comment]
@lonelycode - just a ping on the PR :)

**Comment by lonelycode** [comment]
@natefinch Done :-)

**Comment by natefinch** [comment]
Awesome, thanks!
